version: '3'
services:
  namenode:
    image: sequenceiq/hadoop-docker:latest
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
    volumes:
      - ./data:/data

  datanode1:
    image: sequenceiq/hadoop-docker:latest
    container_name: datanode1
    hostname: datanode1
    volumes:
      - ./data:/data

  datanode2:
    image: sequenceiq/hadoop-docker:latest
    container_name: datanode2
    hostname: datanode2
    volumes:
      - ./data:/data
