version: '3'

services:
  spark-master:
    image: bitnami/spark:latest
    container_name: spark-master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "15002:15002"
    environment:
      - SPARK_MODE=master

  spark-worker:
    image: bitnami/spark:latest
    container_name: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077

  spark-history-server:
    image: bitnami/spark:latest
    container_name: spark-history-server
    ports:
      - "18080:18080"
    environment:
      - SPARK_MODE=history-server
      - SPARK_HISTORY_OPTS="-Dspark.history.fs.logDirectory=file:///tmp/spark-events"
    volumes:
      - spark-events:/tmp/spark-events

volumes:
  spark-events:
